version: "3.7"

x-disabled-service:
  &disabled-service
    image: tianon/true
    restart: "no"
    command: ""
    entrypoint: ""

services:
  geth:
    <<: *disabled-service
  beacon:
    volumes:
      - ./config/prysm/beacon-no-geth.yaml:/config/beacon.yaml:ro
      - ./config/prysm/beacon-no-geth.yaml:/config/beacon-chain.yaml:ro
      - ./data/prysm/beacon:/data
  slasher:
    <<: *disabled-service
  prometheus:
    <<: *disabled-service
  grafana:
    <<: *disabled-service
